### ISSUE TITLE
Plugin Using Wrong Language?

### ISSUE THREAD

**Issue by Cwp1701** [Galedrim/Flow.Launcher.Plugin.Pokedex#1]
Just installed this, I think it's a cool little plugin. But it appears to give me info in French? It also redirects me to a French website when I press enter on an entry.

The first image shows French in Flow Launcher under the Pokemon's stats. The second image shows the website an entry directs me too.

![image](https://github.com/Galedrim/Flow.Launcher.Plugin.Pokedex/assets/54554650/ac0c8de6-9bb4-45c4-a365-26f38621b063)

![image](https://github.com/Galedrim/Flow.Launcher.Plugin.Pokedex/assets/54554650/7963e0e2-8a73-4f28-884b-557acc34c9e2)

**Comment by Galedrim** [comment]
I used it at first for me, I'm French and have some difficulties learning the English name of Pokemon.
I plan to translate it into English and redirect it to an English website like Smogon in the next version
If you have any ideas for improvements, please, tell me :)
