### ISSUE TITLE
Message d'erreur

### ISSUE THREAD

**Issue by Lonu5** [Galedrim/Flow.Launcher.Plugin.Pokedex#2]
J'ai téléchargé pokedex depuis la boutique de plugins et j'ai attendu environ 10 minutes sans que rien ne soit téléchargé ou installé. J'ai alors téléchargé ce plugin non pas depuis le programme mais depuis le site web et lorsque j'ai écrit "pk", j'ai obtenu une erreur, je vais joindre un rapport.
[2024-05-13.txt](https://github.com/Galedrim/Flow.Launcher.Plugin.Pokedex/files/15297617/2024-05-13.txt)

**Comment by Galedrim** [comment]
Est ce que tu es sur FlowLauncher Classique ou Portable ? Je n'ai pas réussi à recréer le "bug". Est ce qu'il est présent sur d'autres plugins téléchargés ? Gitmoji utilise une structure similaires au Pokedex, ça peut être intéressant de voir si cela se reproduit avec

**Comment by Lonu5** [comment]
Bonjour, je ne me souviens plus si j'ai FlowLauncher Classic ou Portable, mais c'est probablement Portable. Je n'ai rien de similaire avec les autres plugins, mais j'ai téléchargé Gitmoji et il s'installait également indéfiniment. J'ai fermé et rouvert FlowLauncher, puis j'ai tapé "gm" et j'ai eu la même erreur
![Снимок экрана 2024-05-19 161246](https://github.com/Galedrim/Flow.Launcher.Plugin.Pokedex/assets/97960541/07b3ef8d-9a77-41a3-8787-63967fb9df33)
[Uploading 2024-05-19.txt…]()
